### ISSUE TITLE
error in 'set_ff_mt_cfg' function

### ISSUE THREAD

**Issue by z8a** [swedishborgie/libmma8451#1]
In 'set_ff_mt_cfg' is called the 'mma8451_get_register' function instead of 'mma8451_get_register' one.

int mma8451_set_ff_mt_cfg(mma8451* device, mma8451_register_ff_mt_cfg* data) {
    if(!mma8451_get_register(device, MMA8451_REGISTER_FF_MT_CFG, (mma8451_register_generic*)data, 0)) {
        return 0;
    }
    return 1;
}

**Comment by swedishborgie** [comment]
Good catch, thanks! Should be fixed now.
